# 本文件由 harbor_setup.sh 脚本生成，请勿手动修改，请运行 harbor_setup.sh 脚本进行更新
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxOTIuMTY4LjQwLjIyNCI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJIYXJib3I5ODc2IiwiZW1haWwiOiJhZG1pbkBzemJpdC5jbiIsImF1dGgiOiJZV1J0YVc0NlNHRnlZbTl5T1RnM05nPT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: harbor-secret
  namespace: dify
type: kubernetes.io/dockerconfigjson
