apiVersion: v1
kind: Secret
metadata:
  name: dify-secrets
  namespace: dify
type: Opaque
stringData:
  SECRET_KEY: "sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U"
  DB_PASSWORD: "difyai123456"
  REDIS_PASSWORD: "difyai123456"
  SANDBOX_API_KEY: "dify-sandbox"
  CODE_EXECUTION_API_KEY: "dify-sandbox"
  WEAVIATE_API_KEY: "WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih"
  WEAVIATE_AUTHENTICATION_APIKEY_ALLOWED_KEYS: "WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih"
  ALIYUN_OSS_ACCESS_KEY: "替换为你的阿里云 OSS Access Key"
  ALIYUN_OSS_SECRET_KEY: "替换为你的阿里云 OSS Access Secret"
  RESEND_API_KEY: "your-resend-api-key"
  S3_ACCESS_KEY: ""
  S3_SECRET_KEY: ""
  UNSTRUCTURED_API_KEY: ""
  PLUGIN_DAEMON_KEY: "lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi"
  PLUGIN_DIFY_INNER_API_KEY: "QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1"
  PLUGIN_ALIYUN_OSS_ACCESS_KEY_ID: "替换为你的阿里云 OSS Access Key"
  PLUGIN_ALIYUN_OSS_ACCESS_KEY_SECRET: "替换为你的阿里云 OSS Secret Key"