apiVersion: v1
kind: Secret
metadata:
  name: dify-secrets
  namespace: dify
type: Opaque
stringData:
  SECRET_KEY: "sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U"
  DB_PASSWORD: "difyai123456"
  REDIS_PASSWORD: "difyai123456"
  SANDBOX_API_KEY: "dify-sandbox"
  CODE_EXECUTION_API_KEY: "dify-sandbox"
  WEAVIATE_API_KEY: "WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih"
  WEAVIATE_AUTHENTICATION_APIKEY_ALLOWED_KEYS: "WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih"
  ALIYUN_OSS_ACCESS_KEY: ""
  ALIYUN_OSS_SECRET_KEY: ""
  RESEND_API_KEY: "your-resend-api-key"
  S3_ACCESS_KEY: ""
  S3_SECRET_KEY: ""
  UNSTRUCTURED_API_KEY: ""