"""empty message

Revision ID: 6d2ac7c72245
Revises: e668df7c7f83
Create Date: 2025-04-01 17:28:41.813083

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2ac7c72245'
down_revision = 'e668df7c7f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_app_logs', schema=None) as batch_op:
        batch_op.drop_index('workflow_app_log_app_idx')
        batch_op.create_index('workflow_app_log_app_idx', ['tenant_id', 'app_id', 'created_at'], unique=False)
        batch_op.create_index('workflow_app_log_workflow_run_idx', ['workflow_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_app_logs', schema=None) as batch_op:
        batch_op.drop_index('workflow_app_log_workflow_run_idx')
        batch_op.drop_index('workflow_app_log_app_idx')
        batch_op.create_index('workflow_app_log_app_idx', ['tenant_id', 'app_id'], unique=False)

    # ### end Alembic commands ###
