"""table upload_files add is_temporary field

Revision ID: a39828e9132f
Revises: d20049ed0af6
Create Date: 2025-03-27 17:23:18.558356

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39828e9132f'
down_revision = 'd20049ed0af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_published_apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', models.types.StringUUID(), nullable=False))
        batch_op.add_column(sa.Column('conversation_id', models.types.StringUUID(), nullable=True))
        batch_op.add_column(sa.Column('file_key', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('mimetype', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('original_url', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=False))

    with op.batch_alter_table('workflow_conversation_variables', schema=None) as batch_op:
        batch_op.drop_index('workflow_conversation_variables_app_id_idx')
        batch_op.drop_index('workflow_conversation_variables_created_at_idx')
        batch_op.create_index('workflow__conversation_variables_app_id_idx', ['app_id'], unique=False)
        batch_op.create_index('workflow__conversation_variables_created_at_idx', ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_conversation_variables', schema=None) as batch_op:
        batch_op.drop_index('workflow__conversation_variables_created_at_idx')
        batch_op.drop_index('workflow__conversation_variables_app_id_idx')
        batch_op.create_index('workflow_conversation_variables_created_at_idx', ['created_at'], unique=False)
        batch_op.create_index('workflow_conversation_variables_app_id_idx', ['app_id'], unique=False)

    with op.batch_alter_table('tool_published_apps', schema=None) as batch_op:
        batch_op.drop_column('size')
        batch_op.drop_column('name')
        batch_op.drop_column('original_url')
        batch_op.drop_column('mimetype')
        batch_op.drop_column('file_key')
        batch_op.drop_column('conversation_id')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
