"""add is_temporary field in uploda_file table

Revision ID: 95d05ec84c4e
Revises: a91b476a53de
Create Date: 2025-04-09 13:05:31.713166

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d05ec84c4e'
down_revision = 'a91b476a53de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_temporary', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_files', schema=None) as batch_op:
        batch_op.drop_column('is_temporary')

    # ### end Alembic commands ###
