"""table upload_files add is_temporary field

Revision ID: e668df7c7f83
Revises: a39828e9132f
Create Date: 2025-03-27 17:41:41.207393

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e668df7c7f83'
down_revision = 'a39828e9132f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_temporary', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_files', schema=None) as batch_op:
        batch_op.drop_column('is_temporary')

    # ### end Alembic commands ###
